config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"

  resources :lists, only: [:new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # add a new bookmark (movie/list pair) to an existing list
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  # delete a bookmark from a list
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete
    redirect_to list_path(@bookmark.list.id)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :destroy]
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h2>Create a new bookmark</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinephiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%# fonts from Adobe: "Le Havre" regular and bold, + "Tuna" %>
    <link rel="stylesheet" href="https://use.typekit.net/vmf7kyk.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner justify-content-center">
  <h1>CINEPHILES</h1>
  <p>curate your own movie collections</p>
</div>

<div class="container">
  <br>
  <% @lists.each do |list| %>
    <p><%= link_to list.name, list_path(list.id) %></p>
  <% end %>

  <h4>Create your own list</h4>

  <%= simple_form_for [ @list ] do |f| %>
    <p>Give your list a fitting name</p>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "CREATE LIST", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h4>Create your own list of movies:</h4>

<%= simple_form_for [ @list ] do |f| %>
  <p>Give your list a fitting name</p>
  <%= f.input :name %>
  <%= f.submit "CREATE FORM", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <%= @list.name  %>
</div>
  <br>


  <% @list.bookmarks.each do |bookmark| %>
    <img src="<% bookmark.movie.poster_url %>" alt="<% bookmark.movie.title %> movie poster">
    <h4><%= bookmark.movie.title.upcase %></h4>
    <p><%= bookmark.movie.overview %></p>
    <p><%= bookmark.comment %></p>
    <h2><%= bookmark.movie.rating %></h2>
    <i class="far fa-trash-alt"></i>
    <%= link_to "Delete #{bookmark.movie.title}", bookmark_path(bookmark.id), method: :delete %>
    <br>
  <% end %>
  <br>
  <p>Add a movie</p>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit "add movie", class: "btn btn-primary" %>
  <% end %>
  <br>
  <%= link_to "Back to all lists", root_path %>
  <br>
  <br>
  <%= link_to "Delete #{@list.name}",
              list_path(@list.id),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</div>